# Setup
title:               Madchan
tagline:             'A podcast about madness'
description:         'We talk about madness over and over again, but expect different results.'
url:                 http://madchan.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jarrod Jeffrey Ingram
  url:               https://github.com/hori-kun
  email:             jarrod.jeffi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
